import React from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { fetchUser } from "@/lib/actions/user.actions";
import { currentUser } from "@clerk/nextjs";
import { redirect } from "next/navigation";

import "./globals.css";

import TopBar from "@/layout/TopBar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const user = await currentUser();
  if (!user) return null;
  const userInfo = await fetchUser(user.id);
  if (!userInfo?.onboarded) redirect("/onboarding");

  return (
    <ClerkProvider>
      <html lang='en' className="bg-gray-100 h-screen">

        <body className="">

          <TopBar />

          {children}

        </body>
      </html>
    </ClerkProvider>
  );
}