import { ClerkProvider } from "@clerk/nextjs"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

//Dùng tailwind phải import file này
import "../(root)/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className="h-screen bg-gray-100">
          <div className="py-10">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
